    - name: Inicializar configuración de pmbootstrap
      run: |
        mkdir -p ~/.config
        # Genera el archivo de configuración con los parámetros válidos actuales
        cat <<EOF > ~/.config/pmbootstrap.cfg
        [pmbootstrap]
        aports = /home/runner/work/pmbootstrap_work/cache_aports
        work = /home/runner/work/pmbootstrap_work
        jobs = 4
        mirror_alpine = http://dl-cdn.alpinelinux.org/alpine/
        device = samsung-gtowifi
        ui = phosh
        is_default_channel = True
        EOF
        # Ejecuta la inicialización sin preguntas adicionales usando la configuración creada
        pmbootstrap init --jobs=4

    - name: Compilar imagen
      run: |
        pmbootstrap install --as-root

    - name: Exportar archivos .img
      run: |
        pmbootstrap export --dest /home/runner/work/export

    - name: Subir imágenes como artefacto de descarga
      uses: actions/upload-artifact@v4
      with:
        name: imagenes-samsung-gtowifi
        path: /home/runner/work/export/*
