name: Compilar postmarketOS para gtowifi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Instalar dependencias
        shell: bash
        run: |
          set -e

          sudo apt-get update
          sudo apt-get install -y \
            git \
            python3 \
            openssl \
            tar \
            ps

      - name: Descargar pmbootstrap
        shell: bash
        run: |
          set -e

          git clone --depth=1 \
            https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git \
            "$HOME/pmbootstrap"

          mkdir -p "$HOME/.local/bin"

          ln -sf \
            "$HOME/pmbootstrap/pmbootstrap.py" \
            "$HOME/.local/bin/pmbootstrap"

          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Verificar pmbootstrap
        shell: bash
        run: |
          set -e
          pmbootstrap --version

      - name: Inicializar pmbootstrap
        shell: bash
        run: |
          set -e

          mkdir -p "$HOME/.config"

          pmbootstrap init <<EOF
          $HOME/pmbootstrap-work
          edge
          samsung-gtowifi
          phosh
          EOF

      - name: Mostrar configuración
        shell: bash
        run: |
          set -e

          echo "===== CONFIG ====="
          cat "$HOME/.config/pmbootstrap_v3.cfg"
          echo "=================="

      - name: Compilar imagen
        shell: bash
        run: |
          set -e

          pmbootstrap install --no-cross

      - name: Exportar imagen
        shell: bash
        run: |
          set -e

          mkdir -p "$GITHUB_WORKSPACE/export"

          pmbootstrap export "$GITHUB_WORKSPACE/export"

      - name: Mostrar archivos generados
        shell: bash
        run: |
          set -e

          echo "===== ARCHIVOS ====="

          find "$GITHUB_WORKSPACE/export" \
            -type f \
            -print

          echo "===================="

      - name: Subir imágenes
        uses: actions/upload-artifact@v4
        with:
          name: imagenes-samsung-gtowifi
          path: ${{ github.workspace }}/export/
          if-no-files-found: error
